################################################################################
# ML.NET's PR validation build
################################################################################

resources:
  containers:
  - container: CentosContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-mlnet-8bba86b-20190314145033
  
  - container: UbuntuContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-mlnet-207e097-20190312152303

jobs:
- template: /build/ci/job-template.yml
  parameters:
    name: Centos_x64_NetCoreApp30
    buildScript: ./build.sh
    container: CentosContainer
    customMatrixes:
      Debug_Build:
        _configuration: Debug-Intrinsics
        _config_short: DI
        _includeBenchmarkData: false
      Release_Build:
        _configuration: Release-Intrinsics
        _config_short: RI
        _includeBenchmarkData: true
    pool:
      name: Hosted Ubuntu 1604

- template: /build/ci/job-template.yml
  parameters:
    name: Ubuntu_x64_NetCoreApp21
    buildScript: ./build.sh
    container: UbuntuContainer
    pool:
      name: Hosted Ubuntu 1604

- template: /build/ci/job-template.yml
  parameters:
    name: MacOS_x64_NetCoreApp21
    buildScript: ./build.sh
    pool:
      name: Hosted macOS

- template: /build/ci/job-template.yml
  parameters:
    name: Windows_x64_NetCoreApp30
    buildScript: build.cmd
    customMatrixes:
      Debug_Build:
        _configuration: Debug-Intrinsics
        _config_short: DI
        _includeBenchmarkData: false
      Release_Build:
        _configuration: Release-Intrinsics
        _config_short: RI
        _includeBenchmarkData: true
    pool:
      name: NetCorePublic-Pool
      queue: buildpool.windows.10.amd64.vs2017.open

- template: /build/ci/job-template.yml
  parameters:
    name: Windows_x64_NetCoreApp21
    buildScript: build.cmd
    pool:
      name: Hosted VS2017

- template: /build/ci/job-template.yml
  parameters:
    name: Windows_x64_NetFx461
    buildScript: build.cmd
    customMatrixes:
      Debug_Build:
        _configuration: Debug-netfx
        _config_short: DFX
        _includeBenchmarkData: false
      Release_Build:
        _configuration: Release-netfx
        _config_short: RFX
        _includeBenchmarkData: false
    pool:
      name: Hosted VS2017

- template: /build/ci/job-template.yml
  parameters:
    name: Windows_x86_NetCoreApp21
    architecture: x86
    buildScript: build.cmd
    pool:
      name: Hosted VS2017
