################################################################################
# ML.NET's PR validation build
################################################################################

pr:
  branches:
    include:
    - main
    - feature/*
    - release/*
  paths:
    include:
    - '*'
    exclude:
    - '**.md'
    - .github/*
    - docs/*
    - LICENSE
    - THIRD-PARTY-NOTICES.TXT

trigger:
  branches:
    include:
    - main
    - feature/*
    - release/*
  paths:
    include:
    - '*'
    exclude:
    - '**.md'
    - .github/*
    - docs/*
    - LICENSE
    - THIRD-PARTY-NOTICES.TXT

resources:
  containers:
  - container: CentosContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream8-mlnet

  - container: UbuntuContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-mlnet

  - container: UbuntuCrossArmContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-mlnet-cross-arm

  - container: UbuntuCrossArm64Container
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-mlnet-cross-arm64

jobs:
- template: /build/ci/job-template.yml
  parameters:
    architecture: arm
    name: Ubuntu_x64_cross_arm
    buildScript: ./build.sh
    container: UbuntuCrossArmContainer
    customMatrixes:
      Debug_Build:
        _configuration: Debug
        _config_short: DI
        _includeBenchmarkData: false
        _targetFramework: net8.0
      Release_Build:
        _configuration: Release
        _config_short: RI
        _includeBenchmarkData: true
        _targetFramework: net8.0
    innerLoop: true
    pool:
      name: NetCore-Public
      demands: ImageOverride -equals build.Ubuntu.2204.amd64.open
    helixQueue: Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7

- template: /build/ci/job-template.yml
  parameters:
    architecture: arm64
    name: Ubuntu_x64_cross_arm64
    buildScript: ./build.sh
    container: UbuntuCrossArm64Container
    customMatrixes:
      Debug_Build:
        _configuration: Debug
        _config_short: DI
        _includeBenchmarkData: false
        _targetFramework: net8.0
      Release_Build:
        _configuration: Release
        _config_short: RI
        _includeBenchmarkData: true
        _targetFramework: net8.0
    innerLoop: true
    pool:
      name: NetCore-Public
      demands: ImageOverride -equals build.Ubuntu.2204.amd64.open
    helixQueue: Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04-helix-arm64v8

- template: /build/ci/job-template.yml
  parameters:
    name: Centos_x64
    buildScript: ./build.sh
    container: CentosContainer
    innerLoop: true
    pool:
      name: NetCore-Public
      demands: ImageOverride -equals build.Ubuntu.2204.amd64.open
    helixQueue: Ubuntu.2204.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream9-mlnet-helix

- template: /build/ci/job-template.yml
  parameters:
    name: Ubuntu_x64
    buildScript: ./build.sh
    container: UbuntuContainer
    innerLoop: true
    pool:
      name: NetCore-Public
      demands: ImageOverride -equals build.Ubuntu.2204.amd64.open
    helixQueue: Ubuntu.2204.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04-mlnet-helix

- template: /build/ci/job-template.yml
  parameters:
    name: MacOS_x64
    buildScript: ./build.sh
    innerLoop: true
    pool:
      vmImage: macOS-13
    helixQueue: OSX.13.Amd64.Open

- template: /build/ci/job-template.yml
  parameters:
    architecture: arm64
    name: MacOS_cross_arm64
    buildScript: ./build.sh
    customMatrixes:
      Debug_Build:
        _configuration: Debug
        _config_short: DI
        _includeBenchmarkData: false
        _targetFramework: net8.0
      Release_Build:
        _configuration: Release
        _config_short: RI
        _includeBenchmarkData: true
        _targetFramework: net8.0
    innerLoop: true
    pool:
      vmImage: macOS-13
    helixQueue: OSX.13.Arm64.Open

- template: /build/ci/job-template.yml
  parameters:
    architecture: arm64
    name: Windows_cross_arm64
    buildScript: build.cmd
    customMatrixes:
      Debug_Build:
        _configuration: Debug
        _config_short: DI
        _includeBenchmarkData: false
        _targetFramework:  net8.0
      Release_Build:
        _configuration: Release
        _config_short: RI
        _includeBenchmarkData: false
        _targetFramework:  net8.0
    innerLoop: true
    vsTestConfiguration: "/Framework:.NETCoreApp,Version=v6.0"
    pool:
      name: NetCore-Public
      demands: ImageOverride -equals 1es-windows-2019-open
    helixQueue: windows.11.arm64.open

- template: /build/ci/job-template.yml
  parameters:
    name: Windows_x64
    buildScript: build.cmd
    innerLoop: true
    vsTestConfiguration: "/Framework:.NETCoreApp,Version=v3.1"
    pool:
      name: NetCore-Public
      demands: ImageOverride -equals 1es-windows-2019-open
    helixQueue: Windows.10.Amd64.Open

- template: /build/ci/job-template.yml
  parameters:
    name: Windows_x64_NetFx461
    buildScript: build.cmd
    customMatrixes:
      Debug_Build:
        _configuration: Debug
        _config_short: DFX
        _includeBenchmarkData: false
        _targetFramework: net462
      Release_Build:
        _configuration: Release
        _config_short: RFX
        _includeBenchmarkData: false
        _targetFramework: net462
    innerLoop: true
    vsTestConfiguration: "/Framework:.NETCoreApp,Version=v4.0"
    pool:
      name: NetCore-Public
      demands: ImageOverride -equals 1es-windows-2019-open
    helixQueue: Windows.10.Amd64.Open

- template: /build/ci/job-template.yml
  parameters:
    name: Windows_x86
    architecture: x86
    buildScript: build.cmd
    innerLoop: true
    vsTestConfiguration: "/Framework:.NETCoreApp,Version=v3.1"
    pool:
      name: NetCore-Public
      demands: ImageOverride -equals 1es-windows-2019-open
    helixQueue: Windows.10.Amd64.Open
