################################################################################
# ML.NET's PR validation build
################################################################################

resources:
  containers:
  - container: CentosContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-mlnet-8bba86b-20190314145033

  - container: UbuntuContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-mlnet-20200515184230-2c829e8

  - container: UbuntuCrossArmContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-mlnet-cross-arm-20210512124625-2e59a5f

  - container: UbuntuCrossArm64Container
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-mlnet-cross-arm64-20210512124625-2e59a5f

jobs:
- template: /build/ci/job-template.yml
  parameters:
    architecture: arm
    name: Ubuntu_x64_cross_arm_NetCoreApp31
    buildScript: ./build.sh
    container: UbuntuCrossArmContainer
    customMatrixes:
      Debug_Build:
        _configuration: Debug
        _config_short: DI
        _includeBenchmarkData: false
        _targetFramework: netcoreapp3.1
      Release_Build:
        _configuration: Release
        _config_short: RI
        _includeBenchmarkData: true
        _targetFramework: netcoreapp3.1
    innerLoop: true
    pool:
      vmImage: ubuntu-18.04
    helixQueue: Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-20210531091521-97d8652

- template: /build/ci/job-template.yml
  parameters:
    architecture: arm64
    name: Ubuntu_x64_cross_arm64_NetCoreApp31
    buildScript: ./build.sh
    container: UbuntuCrossArm64Container
    customMatrixes:
      Debug_Build:
        _configuration: Debug
        _config_short: DI
        _includeBenchmarkData: false
        _targetFramework: netcoreapp3.1
      Release_Build:
        _configuration: Release
        _config_short: RI
        _includeBenchmarkData: true
        _targetFramework: netcoreapp3.1
    innerLoop: true
    pool:
      vmImage: ubuntu-18.04
    helixQueue: Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- template: /build/ci/job-template.yml
  parameters:
    name: Centos_x64_NetCoreApp31
    buildScript: ./build.sh
    container: CentosContainer
    innerLoop: true
    pool:
      vmImage: ubuntu-18.04
    helixQueue: Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-mlnet-helix-20210528183707-dde38af

- template: /build/ci/job-template.yml
  parameters:
    name: Ubuntu_x64_NetCoreApp31
    buildScript: ./build.sh
    container: UbuntuContainer
    innerLoop: true
    pool:
      vmImage: ubuntu-18.04
    helixQueue: Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-mlnet-helix-20210528184647-dde38af

- template: /build/ci/job-template.yml
  parameters:
    name: MacOS_x64_NetCoreApp31
    buildScript: ./build.sh
    innerLoop: true
    pool:
      vmImage: macOS-10.15
    helixQueue: OSX.1015.Amd64.Open

- template: /build/ci/job-template.yml
  parameters:
    architecture: arm64
    name: MacOS_cross_arm64_Net6
    buildScript: ./build.sh
    customMatrixes:
      Debug_Build:
        _configuration: Debug
        _config_short: DI
        _includeBenchmarkData: false
        _targetFramework: net6.0
      Release_Build:
        _configuration: Release
        _config_short: RI
        _includeBenchmarkData: true
        _targetFramework: net6.0
    innerLoop: true
    pool:
      vmImage: macOS-10.15
    helixQueue: OSX.1100.Arm64.Open

- template: /build/ci/job-template.yml
  parameters:
    name: Windows_x64_NetCoreApp31
    buildScript: build.cmd
    innerLoop: true
    vsTestConfiguration: "/Framework:.NETCoreApp,Version=v3.1"
    pool:
      vmImage: windows-2019
    helixQueue: Windows.10.Amd64.Open

- template: /build/ci/job-template.yml
  parameters:
    name: Windows_x64_NetFx461
    buildScript: build.cmd
    customMatrixes:
      Debug_Build:
        _configuration: Debug
        _config_short: DFX
        _includeBenchmarkData: false
        _targetFramework: net461
      Release_Build:
        _configuration: Release
        _config_short: RFX
        _includeBenchmarkData: false
        _targetFramework: net461
    innerLoop: true
    vsTestConfiguration: "/Framework:.NETCoreApp,Version=v4.0"
    pool:
      vmImage: windows-2019
    helixQueue: Windows.10.Amd64.Open

- template: /build/ci/job-template.yml
  parameters:
    name: Windows_x86_NetCoreApp31
    architecture: x86
    buildScript: build.cmd
    innerLoop: true
    vsTestConfiguration: "/Framework:.NETCoreApp,Version=v3.1"
    pool:
      vmImage: windows-2019
    helixQueue: Windows.10.Amd64.Open
