phases:
- template: /build/ci/phase-template.yml
  parameters:
    name: Linux
    buildScript: ./build.sh
    dockerImage: microsoft/dotnet-buildtools-prereqs:centos-7-b46d863-20180719033416

- template: /build/ci/phase-template.yml
  parameters:
    name: Windows_NT
    buildScript: build.cmd
    queue:
      name: Hosted VS2017
      demands:
        - agent.os -equals Windows_NT
