################################################################################
# ML.NET's PR validation build
################################################################################

resources:
  containers:
  - container: LinuxContainer
    image: microsoft/dotnet-buildtools-prereqs:centos-7-b46d863-20180719033416

phases:
- template: /build/ci/phase-template.yml
  parameters:
    name: Windows_x64
    buildScript: build.cmd
    queue:
      name: Hosted VS2017
