resources:
  containers:
  - container: LinuxContainer
    image: microsoft/dotnet-buildtools-prereqs:centos-7-d485f41-20173404063424

phases:
- template: /build/ci/phase-template.yml
  parameters:
    name: Linux
    buildScript: ./build.sh
    queue:
      name: DotNetCore-Linux
      container: LinuxContainer

- template: /build/ci/phase-template.yml
  parameters:
    name: Windows_NT
    buildScript: build.cmd
    queue:
      name: Hosted VS2017 

- template: /build/ci/phase-template.yml
  parameters:
    name: MacOS
    buildScript: ./build.sh
    queue:
      name: DotNetCore-Mac
