################################################################################
# ML.NET's PR validation build
################################################################################

resources:
  containers:
  - container: LinuxContainer
    image: microsoft/dotnet-buildtools-prereqs:centos-7-b46d863-20180719033416

phases:
- template: /build/ci/phase-template.yml
  parameters:
    name: core30
    buildScript: build.cmd
    customMatrixes:
      Build_Debug_Intrinsics:
        _configuration: Debug-Intrinsics
        _config_short: DI
      Build_Release_Intrinsics:
        _configuration: Release-Intrinsics
        _config_short: RI
    queue:
      name: Hosted VS2017

- template: /build/ci/phase-template.yml
  parameters:
    name: Linux
    buildScript: ./build.sh
    queue:
      name: Hosted Ubuntu 1604
      container: LinuxContainer

- template: /build/ci/phase-template.yml
  parameters:
    name: MacOS
    buildScript: ./build.sh
    queue:
      name: Hosted macOS

- template: /build/ci/phase-template.yml
  parameters:
    name: Windows_NetFx
    buildScript: build.cmd
    customMatrixes:
      Build_Debug_netfx:
        _configuration: Debug-netfx
        _config_short: DFX
      Build_Release_netfx:
        _configuration: Release-netfx
        _config_short: RFX  
    queue:
      name: Hosted VS2017

- template: /build/ci/phase-template.yml
  parameters:
    name: Windows_x64
    buildScript: build.cmd
    queue:
      name: Hosted VS2017

- template: /build/ci/phase-template.yml
  parameters:
    name: Windows_x86
    architecture: x86
    buildScript: build.cmd
    queue:
      name: Hosted VS2017