################################################################################
# ML.NET's PR validation build
################################################################################

resources:
  containers:
  - container: CentosContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-mlnet-8bba86b-20190314145033
  
  - container: UbuntuContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-mlnet-207e097-20190312152303

jobs:
- template: /build/ci/job-template.yml
  parameters:
    name: Windows_x64_NetCoreApp31
    buildScript: build.cmd
    customMatrixes:
      Release_Build:
        _configuration: Release-netcoreapp3_1
        _config_short: RI
        _includeBenchmarkData: true
        _targetFramework: netcoreapp3.1
    innerLoop: false
    runSpecific: false
    vsTestConfiguration: "/Framework:.NETCoreApp,Version=v3.0"
    pool:
      name: Hosted VS2017

- template: /build/ci/job-template.yml
  parameters:
    name: Windows_x64_NetCoreApp21
    buildScript: build.cmd
    innerLoop: false
    runSpecific: false
    vsTestConfiguration: "/Framework:.NETCoreApp,Version=v2.1"
    pool:
      name: Hosted VS2017

- template: /build/ci/job-template.yml
  parameters:
    name: Windows_x86_NetCoreApp21
    architecture: x86
    buildScript: build.cmd
    innerLoop: false
    runSpecific: false
    vsTestConfiguration: "/Framework:.NETCoreApp,Version=v2.1"
    pool:
      name: Hosted VS2017
