################################################################################
# ML.NET's PR validation build
################################################################################

resources:
  containers:  
  - container: UbuntuContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-mlnet-20200515184230-2c829e8

jobs:
- template: /build/ci/job-template.yml
  parameters:
    name: Ubuntu_x64_NetCoreApp21
    buildScript: ./build.sh
    container: UbuntuContainer
    innerLoop: true
    pool:
      name:  Hosted Ubuntu 1604

- template: /build/ci/job-template.yml
  parameters:
    name: MacOS_x64_NetCoreApp21
    buildScript: ./build.sh
    innerLoop: true
    pool:
      name: Hosted macOS
