// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.ML.CLI.Templates.Console
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ConsoleHelper : ConsoleHelperBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing Micro" +
                    "soft.Data.DataView;\r\nusing Microsoft.ML.Core.Data;\r\nusing Microsoft.ML.Data;\r\n\r\n" +
                    "namespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            this.Write("\r\n{\r\n    public static class ConsoleHelper\r\n    {\r\n        public static void Pri" +
                    "ntPrediction(string prediction)\r\n        {\r\n            Console.WriteLine($\"****" +
                    "*********************************************\");\r\n            Console.WriteLine(" +
                    "$\"Predicted : {prediction}\");\r\n            Console.WriteLine($\"*****************" +
                    "********************************\");\r\n        }\r\n\r\n        public static void Pri" +
                    "ntRegressionPredictionVersusObserved(string predictionCount, string observedCoun" +
                    "t)\r\n        {\r\n            Console.WriteLine($\"---------------------------------" +
                    "----------------\");\r\n            Console.WriteLine($\"Predicted : {predictionCoun" +
                    "t}\");\r\n            Console.WriteLine($\"Actual:     {observedCount}\");\r\n         " +
                    "   Console.WriteLine($\"-------------------------------------------------\");\r\n   " +
                    "     }\r\n\r\n        public static void PrintRegressionMetrics(string name, Regress" +
                    "ionMetrics metrics)\r\n        {\r\n            Console.WriteLine($\"****************" +
                    "*********************************\");\r\n            Console.WriteLine($\"*       Me" +
                    "trics for {name} regression model      \");\r\n            Console.WriteLine($\"*---" +
                    "---------------------------------------------\");\r\n            Console.WriteLine(" +
                    "$\"*       LossFn:        {metrics.LossFn:0.##}\");\r\n            Console.WriteLine" +
                    "($\"*       R2 Score:      {metrics.RSquared:0.##}\");\r\n            Console.WriteL" +
                    "ine($\"*       Absolute loss: {metrics.L1:#.##}\");\r\n            Console.WriteLine" +
                    "($\"*       Squared loss:  {metrics.L2:#.##}\");\r\n            Console.WriteLine($\"" +
                    "*       RMS loss:      {metrics.Rms:#.##}\");\r\n            Console.WriteLine($\"**" +
                    "***********************************************\");\r\n        }\r\n\r\n        public " +
                    "static void PrintBinaryClassificationMetrics(string name, BinaryClassificationMe" +
                    "trics metrics)\r\n        {\r\n            Console.WriteLine($\"*********************" +
                    "***************************************\");\r\n            Console.WriteLine($\"*   " +
                    "    Metrics for {name} binary classification model      \");\r\n            Console" +
                    ".WriteLine($\"*-----------------------------------------------------------\");\r\n  " +
                    "          Console.WriteLine($\"*       Accuracy: {metrics.Accuracy:P2}\");\r\n      " +
                    "      Console.WriteLine($\"*       Auc:      {metrics.Auc:P2}\");\r\n            Con" +
                    "sole.WriteLine($\"************************************************************\");" +
                    "\r\n        }\r\n\r\n        public static void PrintMultiClassClassificationMetrics(s" +
                    "tring name, MultiClassClassifierMetrics metrics)\r\n        {\r\n            Console" +
                    ".WriteLine($\"************************************************************\");\r\n  " +
                    "          Console.WriteLine($\"*    Metrics for {name} multi-class classification" +
                    " model   \");\r\n            Console.WriteLine($\"*---------------------------------" +
                    "--------------------------\");\r\n            Console.WriteLine($\"    AccuracyMacro" +
                    " = {metrics.AccuracyMacro:0.####}, a value between 0 and 1, the closer to 1, the" +
                    " better\");\r\n            Console.WriteLine($\"    AccuracyMicro = {metrics.Accurac" +
                    "yMicro:0.####}, a value between 0 and 1, the closer to 1, the better\");\r\n       " +
                    "     Console.WriteLine($\"    LogLoss = {metrics.LogLoss:0.####}, the closer to 0" +
                    ", the better\");\r\n            Console.WriteLine($\"    LogLoss for class 1 = {metr" +
                    "ics.PerClassLogLoss[0]:0.####}, the closer to 0, the better\");\r\n            Cons" +
                    "ole.WriteLine($\"    LogLoss for class 2 = {metrics.PerClassLogLoss[1]:0.####}, t" +
                    "he closer to 0, the better\");\r\n            Console.WriteLine($\"    LogLoss for c" +
                    "lass 3 = {metrics.PerClassLogLoss[2]:0.####}, the closer to 0, the better\");\r\n  " +
                    "          Console.WriteLine($\"**************************************************" +
                    "**********\");\r\n        }\r\n\r\n\r\n        public static void PrintRegressionFoldsAve" +
                    "rageMetrics(string algorithmName,\r\n                                             " +
                    "                 (RegressionMetrics metrics,\r\n                                  " +
                    "                             ITransformer model,\r\n                              " +
                    "                                 IDataView scoredTestData)[] crossValidationResu" +
                    "lts\r\n                                                             )\r\n        {\r\n" +
                    "            var L1 = crossValidationResults.Select(r => r.metrics.L1);\r\n        " +
                    "    var L2 = crossValidationResults.Select(r => r.metrics.L2);\r\n            var " +
                    "RMS = crossValidationResults.Select(r => r.metrics.L1);\r\n            var lossFun" +
                    "ction = crossValidationResults.Select(r => r.metrics.LossFn);\r\n            var R" +
                    "2 = crossValidationResults.Select(r => r.metrics.RSquared);\r\n\r\n            Conso" +
                    "le.WriteLine($\"*****************************************************************" +
                    "********************************************\");\r\n            Console.WriteLine($" +
                    "\"*       Metrics for {algorithmName} Regression model      \");\r\n            Cons" +
                    "ole.WriteLine($\"*---------------------------------------------------------------" +
                    "---------------------------------------------\");\r\n            Console.WriteLine(" +
                    "$\"*       Average L1 Loss:    {L1.Average():0.###} \");\r\n            Console.Writ" +
                    "eLine($\"*       Average L2 Loss:    {L2.Average():0.###}  \");\r\n            Conso" +
                    "le.WriteLine($\"*       Average RMS:          {RMS.Average():0.###}  \");\r\n       " +
                    "     Console.WriteLine($\"*       Average Loss Function: {lossFunction.Average():" +
                    "0.###}  \");\r\n            Console.WriteLine($\"*       Average R-squared: {R2.Aver" +
                    "age():0.###}  \");\r\n            Console.WriteLine($\"*****************************" +
                    "********************************************************************************" +
                    "\");\r\n        }\r\n\r\n        public static void PrintBinaryClassificationFoldsAvera" +
                    "geMetrics(\r\n                                         string algorithmName,\r\n    " +
                    "                                     (BinaryClassificationMetrics metrics,\r\n    " +
                    "                                      ITransformer model,\r\n                     " +
                    "                     IDataView scoredTestData)[] crossValResults\r\n              " +
                    "                                                             )\r\n        {\r\n     " +
                    "       var metricsInMultipleFolds = crossValResults.Select(r => r.metrics);\r\n\r\n " +
                    "           var AccuracyValues = metricsInMultipleFolds.Select(m => m.Accuracy);\r" +
                    "\n            var AccuracyAverage = AccuracyValues.Average();\r\n            var Ac" +
                    "curaciesStdDeviation = CalculateStandardDeviation(AccuracyValues);\r\n            " +
                    "var AccuraciesConfidenceInterval95 = CalculateConfidenceInterval95(AccuracyValue" +
                    "s);\r\n\r\n\r\n            Console.WriteLine($\"***************************************" +
                    "**********************************************************************\");\r\n     " +
                    "       Console.WriteLine($\"*       Metrics for {algorithmName} Binary Classifica" +
                    "tion model      \");\r\n            Console.WriteLine($\"*--------------------------" +
                    "--------------------------------------------------------------------------------" +
                    "--\");\r\n            Console.WriteLine($\"*       Average Accuracy:    {AccuracyAve" +
                    "rage:0.###}  - Standard deviation: ({AccuraciesStdDeviation:#.###})  - Confidenc" +
                    "e Interval 95%: ({AccuraciesConfidenceInterval95:#.###})\");\r\n            Console" +
                    ".WriteLine($\"*******************************************************************" +
                    "******************************************\");\r\n\r\n        }\r\n\r\n        public sta" +
                    "tic void PrintMulticlassClassificationFoldsAverageMetrics(\r\n                    " +
                    "                     string algorithmName,\r\n                                    " +
                    "     (MultiClassClassifierMetrics metrics,\r\n                                    " +
                    "      ITransformer model,\r\n                                          IDataView s" +
                    "coredTestData)[] crossValResults\r\n                                              " +
                    "                             )\r\n        {\r\n            var metricsInMultipleFold" +
                    "s = crossValResults.Select(r => r.metrics);\r\n\r\n            var microAccuracyValu" +
                    "es = metricsInMultipleFolds.Select(m => m.AccuracyMicro);\r\n            var micro" +
                    "AccuracyAverage = microAccuracyValues.Average();\r\n            var microAccuracie" +
                    "sStdDeviation = CalculateStandardDeviation(microAccuracyValues);\r\n            va" +
                    "r microAccuraciesConfidenceInterval95 = CalculateConfidenceInterval95(microAccur" +
                    "acyValues);\r\n\r\n            var macroAccuracyValues = metricsInMultipleFolds.Sele" +
                    "ct(m => m.AccuracyMacro);\r\n            var macroAccuracyAverage = macroAccuracyV" +
                    "alues.Average();\r\n            var macroAccuraciesStdDeviation = CalculateStandar" +
                    "dDeviation(macroAccuracyValues);\r\n            var macroAccuraciesConfidenceInter" +
                    "val95 = CalculateConfidenceInterval95(macroAccuracyValues);\r\n\r\n            var l" +
                    "ogLossValues = metricsInMultipleFolds.Select(m => m.LogLoss);\r\n            var l" +
                    "ogLossAverage = logLossValues.Average();\r\n            var logLossStdDeviation = " +
                    "CalculateStandardDeviation(logLossValues);\r\n            var logLossConfidenceInt" +
                    "erval95 = CalculateConfidenceInterval95(logLossValues);\r\n\r\n            var logLo" +
                    "ssReductionValues = metricsInMultipleFolds.Select(m => m.LogLossReduction);\r\n   " +
                    "         var logLossReductionAverage = logLossReductionValues.Average();\r\n      " +
                    "      var logLossReductionStdDeviation = CalculateStandardDeviation(logLossReduc" +
                    "tionValues);\r\n            var logLossReductionConfidenceInterval95 = CalculateCo" +
                    "nfidenceInterval95(logLossReductionValues);\r\n\r\n            Console.WriteLine($\"*" +
                    "********************************************************************************" +
                    "****************************\");\r\n            Console.WriteLine($\"*       Metrics" +
                    " for {algorithmName} Multi-class Classification model      \");\r\n            Cons" +
                    "ole.WriteLine($\"*---------------------------------------------------------------" +
                    "---------------------------------------------\");\r\n            Console.WriteLine(" +
                    "$\"*       Average MicroAccuracy:    {microAccuracyAverage:0.###}  - Standard dev" +
                    "iation: ({microAccuraciesStdDeviation:#.###})  - Confidence Interval 95%: ({micr" +
                    "oAccuraciesConfidenceInterval95:#.###})\");\r\n            Console.WriteLine($\"*   " +
                    "    Average MacroAccuracy:    {macroAccuracyAverage:0.###}  - Standard deviation" +
                    ": ({macroAccuraciesStdDeviation:#.###})  - Confidence Interval 95%: ({macroAccur" +
                    "aciesConfidenceInterval95:#.###})\");\r\n            Console.WriteLine($\"*       Av" +
                    "erage LogLoss:          {logLossAverage:#.###}  - Standard deviation: ({logLossS" +
                    "tdDeviation:#.###})  - Confidence Interval 95%: ({logLossConfidenceInterval95:#." +
                    "###})\");\r\n            Console.WriteLine($\"*       Average LogLossReduction: {log" +
                    "LossReductionAverage:#.###}  - Standard deviation: ({logLossReductionStdDeviatio" +
                    "n:#.###})  - Confidence Interval 95%: ({logLossReductionConfidenceInterval95:#.#" +
                    "##})\");\r\n            Console.WriteLine($\"***************************************" +
                    "**********************************************************************\");\r\n\r\n   " +
                    "     }\r\n\r\n        public static double CalculateStandardDeviation(IEnumerable<do" +
                    "uble> values)\r\n        {\r\n            double average = values.Average();\r\n      " +
                    "      double sumOfSquaresOfDifferences = values.Select(val => (val - average) * " +
                    "(val - average)).Sum();\r\n            double standardDeviation = Math.Sqrt(sumOfS" +
                    "quaresOfDifferences / (values.Count() - 1));\r\n            return standardDeviati" +
                    "on;\r\n        }\r\n\r\n        public static double CalculateConfidenceInterval95(IEn" +
                    "umerable<double> values)\r\n        {\r\n            double confidenceInterval95 = 1" +
                    ".96 * CalculateStandardDeviation(values) / Math.Sqrt((values.Count() - 1));\r\n   " +
                    "         return confidenceInterval95;\r\n        }\r\n\r\n        public static void P" +
                    "rintClusteringMetrics(string name, ClusteringMetrics metrics)\r\n        {\r\n      " +
                    "      Console.WriteLine($\"*************************************************\");\r\n" +
                    "            Console.WriteLine($\"*       Metrics for {name} clustering model     " +
                    " \");\r\n            Console.WriteLine($\"*-----------------------------------------" +
                    "-------\");\r\n            Console.WriteLine($\"*       AvgMinScore: {metrics.AvgMin" +
                    "Score}\");\r\n            Console.WriteLine($\"*       DBI is: {metrics.Dbi}\");\r\n   " +
                    "         Console.WriteLine($\"*************************************************\")" +
                    ";\r\n        }\r\n\r\n        public static void ConsoleWriteHeader(params string[] li" +
                    "nes)\r\n        {\r\n            var defaultColor = Console.ForegroundColor;\r\n      " +
                    "      Console.ForegroundColor = ConsoleColor.Yellow;\r\n            Console.WriteL" +
                    "ine(\" \");\r\n            foreach (var line in lines)\r\n            {\r\n             " +
                    "   Console.WriteLine(line);\r\n            }\r\n            var maxLength = lines.Se" +
                    "lect(x => x.Length).Max();\r\n            Console.WriteLine(new string(\'#\', maxLen" +
                    "gth));\r\n            Console.ForegroundColor = defaultColor;\r\n        }\r\n\r\n      " +
                    "  public static void ConsoleWriterSection(params string[] lines)\r\n        {\r\n   " +
                    "         var defaultColor = Console.ForegroundColor;\r\n            Console.Foregr" +
                    "oundColor = ConsoleColor.Blue;\r\n            Console.WriteLine(\" \");\r\n           " +
                    " foreach (var line in lines)\r\n            {\r\n                Console.WriteLine(l" +
                    "ine);\r\n            }\r\n            var maxLength = lines.Select(x => x.Length).Ma" +
                    "x();\r\n            Console.WriteLine(new string(\'-\', maxLength));\r\n            Co" +
                    "nsole.ForegroundColor = defaultColor;\r\n        }\r\n\r\n        public static void C" +
                    "onsolePressAnyKey()\r\n        {\r\n            var defaultColor = Console.Foregroun" +
                    "dColor;\r\n            Console.ForegroundColor = ConsoleColor.Green;\r\n            " +
                    "Console.WriteLine(\" \");\r\n            Console.WriteLine(\"Press any key to finish." +
                    "\");\r\n            Console.ReadKey();\r\n        }\r\n\r\n        public static void Con" +
                    "soleWriteException(params string[] lines)\r\n        {\r\n            var defaultCol" +
                    "or = Console.ForegroundColor;\r\n            Console.ForegroundColor = ConsoleColo" +
                    "r.Red;\r\n            const string exceptionTitle = \"EXCEPTION\";\r\n            Cons" +
                    "ole.WriteLine(\" \");\r\n            Console.WriteLine(exceptionTitle);\r\n           " +
                    " Console.WriteLine(new string(\'#\', exceptionTitle.Length));\r\n            Console" +
                    ".ForegroundColor = defaultColor;\r\n            foreach (var line in lines)\r\n     " +
                    "       {\r\n                Console.WriteLine(line);\r\n            }\r\n        }\r\n\r\n" +
                    "        public static void ConsoleWriteWarning(params string[] lines)\r\n        {" +
                    "\r\n            var defaultColor = Console.ForegroundColor;\r\n            Console.F" +
                    "oregroundColor = ConsoleColor.DarkMagenta;\r\n            const string warningTitl" +
                    "e = \"WARNING\";\r\n            Console.WriteLine(\" \");\r\n            Console.WriteLi" +
                    "ne(warningTitle);\r\n            Console.WriteLine(new string(\'#\', warningTitle.Le" +
                    "ngth));\r\n            Console.ForegroundColor = defaultColor;\r\n            foreac" +
                    "h (var line in lines)\r\n            {\r\n                Console.WriteLine(line);\r\n" +
                    "            }\r\n        }\r\n\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }

public string Namespace {get;set;}

    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class ConsoleHelperBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
