name: Backport PR to branch
on:
  issue_comment:
    types: [created]
  schedule:
    # once a day at 13:00 UTC to cleanup old runs
    - cron: '0 13 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write

jobs:
  backport:
    if: ${{ contains(github.event.comment.body, '/backport to') || github.event_name == 'schedule' }}
    uses: dotnet/arcade/.github/workflows/backport-base.yml@main
    with:
      pr_description_template: |
        Backport of #%source_pr_number% to %target_branch%

        /cc %cc_users%

        ## Customer Impact

        ## Testing

        ## Risk
